### ISSUE TITLE
Support saving sessions outside of git repos

### ISSUE THREAD

**Issue by erikw** [superDross/ticket.vim#10]
It would be useful to be able to save a session based on only the current path and not the git branch, when there is no git project.

If this was supported, one can streamline the working habbits by being able to always use `:SaveSession`, even outside git repos. 

Currently one gets this error message:
```
Error detected while processing function CreateSession[1]..GetTicketFilePath[1]..CheckIfGitRepo:
line    9:
The current directory is not a git repository
```

It's convention to map `:SaveSession` to `ctrl+s` and I would like to be able to use this everywhere!
```vim
nnoremap <silent> <C-s> :execute ':SaveSession' <bar> echo "Session saved"<CR>
```

**Comment by superDross** [comment]
I think this is outside the scope of the project.

This plugin saves sessions on a per git-branch basis so one can easily switch between sessions in many different feature/bug-fix branches over a given time. Using this plugin outside a git repo therefore does not make sense.

If you want a generic session manager there are other plugins out there. The excellent obsession plugin comes to mind: https://github.com/tpope/vim-obsession or this https://github.com/xolox/vim-session

Otherwise manually maintaining your own sessions may be of interest. See `:help mksession` for more info.

**Comment by superDross** [comment]
Having thought about this more, it may be a useful feature to have as it no longer require using multiple plugins for session management.

A solution would be to determine if it is not a git repo then simply name the session file `main.vim` this will also allow it to continue to be usable if the directory is initialised as a git repo in the future.

**Comment by erikw** [comment]
🥳 thank you @superDross. In a quick test run it works good. I'll report back if I see something strange :)
