### ISSUE TITLE
Filetype / syntax not restored

### ISSUE THREAD

**Issue by erikw** [superDross/ticket.vim#21]
Hey,

for me the syntax is not on when loading a saved session. I noticed that when I check `:set filetype?` it's empty as well. I'm on neovim `0.7.2` and the same for vim `8.2`.

If I then do `:edit` in a buffer the syntax and filetype is set correctly. Does this happen for other peoples as well?

I have this setting enable:
```viml
let g:auto_ticket = 1

```

**Comment by superDross** [comment]
I don't use `g:auto_ticket` anymore hence why this bug escaped me.

This seems to be occurring due to a race condition associated with `VimEnter` autocommand. This autocommand is executed after vim has started up but not necessarily after all of your vimrc  has loaded. This explains why the filetype has not been set and why my various language specific plugins don't work.

A hacky fix would be to essentially sleep for a set period of time:
```vim
autocmd VimEnter * call timer_start(200, { tid -> execute(OpenSession())})
```
However, this is not the best solution as the time is variable based upon the git repo and session size.

I'll look into this further and find a better solution.

**Comment by superDross** [comment]
@erikw please reopen this ticket if there are issues with the implementation

**Comment by erikw** [comment]
So far this fix made it, thanks!!
