### ISSUE TITLE
backticks don't work in fish shell

### ISSUE THREAD

**Issue by mdi** [superDross/ticket.vim#34]
This is a great plugin, but the backticks (``) don't work in the fish shell. For example, the `ticket#git#GetRepoName` function returns 
<img width="517" alt="Screen Shot 2022-08-30 at 14 36 22" src="https://user-images.githubusercontent.com/524808/187516460-78a89b38-0beb-45b9-ad16-715fd76090ed.png">

**Comment by superDross** [comment]
I just installed fish shell and have had no issues using this plugin. This makes me think this is not due to the shell. There is likely another reason.

You will have to supply a lot more details to allow me to help debug and fix this issue.
EDIT: nevermind I see the issue. I'll use $() in place of ``. This should fix it.

**Comment by superDross** [comment]
@mdi could you pull down https://github.com/superDross/ticket.vim/pull/35 and confirm this fix works for you?

**Comment by mdi** [comment]
@superDross yes, that fixes it.
