### ISSUE TITLE
Wrong session filename when git branch has `/` => can't load with `:OpenSession`

### ISSUE THREAD

**Issue by erikw** [superDross/ticket.vim#53]
When being on a git branch named `2022/16`, `:SaveSession` will create a file `16.vim`. `:OpenSession` can't find this file, as it probably looks for `2022/16.vim`.

As I think it's now allowed to have a slash in a filename itself on UNIX-like system, maybe some normalization should be applied to the filename like replacing slashes from the git-branch with `:` or `-`. Though this would conflict with a file saved from a branch actually named `2022-16`. Maybe better hash/encode the branch name to create the filename? Though this makes the UX worse as one can't simply `ls` the directory to find which branches are saved to files.

**Comment by superDross** [comment]
So the reason it is implemented this way is because I name my branches with a prefix that I want to always remove e.g. `fix/unholy-bug`, `feature/cool-new-endpoint`. The logic is to remove everything that precedes the forward slash. This means `fix/branch-name` session becomes `branch-name.vim` when it is saved. In hindsight this wasn't the smartest solution to that problem. Especially as this gained users beyond myself.

I don't like the idea of hash/encoding them because, as you say, it reduces the readability of the directory. Additionally it will make supporting backward compatibility somewhat more cumbersome as all old session files won't be hashed and all new files will be.

I think I will take the approach of normalising the data. Probably by replacing `/` with `%` as I don't imagine anyone is creating branches with percentage signs and the symbols look quite similar.

Requirements:
- Ensure all branches containing `/` as a substring are replaced with `%` when opening and saving session/note files
- If a user tries to save a session/note file with a branch name containing the substring `%` supply an error message explaining it is impossible
- Create multiple tests to tease out any edge cases
-  Update documentation both in vim help and README very clearly stating this breaks compatability with any old `/` branch naming conventions
- Bump to a major version as this will be partially incompatible with old versions of the plugin


Optional:
- A `g:ticket_legacy_filenames` option that maintains the legacy file naming logic and document it
- Consider having a deprecation message within vim when saving session for the first time after updating stating the change (not sure whether this is even feasible)

**Comment by superDross** [comment]
@erikw Can you pull down the below branch and test that this fixes the issue?

FYI saving a branch named `16/2022` should result in a `16%2022.vim` file being created when saving a session.

https://github.com/superDross/ticket.vim/pull/54/files

**Comment by erikw** [comment]
Hey,

I have this a quick test and it seems too work! Thank you 😊
