### ISSUE TITLE
"This buffer already exists" with Nvim Tree

### ISSUE THREAD

**Issue by harrisoncramer** [superDross/ticket.vim#8]
The plugin throws an error when saving and restoring sessions that include Nvim-Tree:

```
"plugin/ticket.vim" 165L, 3936C
Error detected while processing /home/harrycramer/.tickets/ticket.vim/master.vim:
line   34:
E95: Buffer with this name already exists
```
Upon opening the session, there is a new blank buffer in place of the Nvim-Tree, which displays this when I print the buffers (I've got a few other files open here):

```
:buffers
  5  a   "plugin/ticket.vim"            line 1
  6 #a   ".gitignore"                   line 1
  7 %a   "[No Name]"                    line 1
```

**Comment by superDross** [comment]
Can you try and open vim, manually create the session via `:mks ~/sess.vim`, close vim and reopen the session with `vim -S ~/sess.vim`?

I imagine it still won't work because I suspect they are using temporary buffers (e.g. `buftype=nofile` or some other special buffer type). If so, this is an issue with Nvim-Tree and how they configure their buffers.

FWIW I get a similar issue when using `tagbar`, even when manually creating sessions via native command `mks`. I simply don't save sessions with it present and I don't use it very often so don't consider it an issue.

**Comment by harrisoncramer** [comment]
You're right, thanks for the quick reply. Had to do some hacky workarounds with Nvim-Tree.

**Comment by superDross** [comment]
@harrisoncramer out of curiosity, what is the workaround you are using to get it working?
